code-hike/codehike

.prettierignore
package.json
packages/mini-editor/package.json
packages/mini-editor/src/editor-frame.tsx
packages/mini-terminal/src/mini-terminal-transition.tsx
packages/scroller/package.json
packages/scroller/src/index.tsx
packages/scroller/tsconfig.json
site/package.json
site/pages/demo/apple-landing.js
site/src/demo-apple-landing/editor-steps.js
site/src/demo-apple-landing/index.js
site/src/demo-apple-landing/index.module.css
site/src/demo-apple-landing/steps/lorem.0.js
site/src/demo-apple-landing/steps/lorem.1.js
site/src/demo-apple-landing/steps/lorem.2.js
site/src/demo-apple-landing/terminal-steps.js
yarn.lock

Adding a demo similar to apple's landing page.
https://twitter.com/pomber/status/1275294119234080770

Apple demo

---

.github/workflows/release.yml
lerna.json
package.json
packages/script/build.js

<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.32.323f72f.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.32.323f72f.0
npm install @code-hike/code-diff@0.3.0--canary.32.323f72f.0
npm install @code-hike/mini-browser@0.3.0--canary.32.323f72f.0
npm install @code-hike/mini-editor@0.3.0--canary.32.323f72f.0
npm install @code-hike/mini-frame@0.3.0--canary.32.323f72f.0
npm install @code-hike/mini-terminal@0.3.0--canary.32.323f72f.0
npm install @code-hike/player@0.3.0--canary.32.323f72f.0
npm install @code-hike/script@0.3.0--canary.32.323f72f.0
npm install @code-hike/scroller@0.3.0--canary.32.323f72f.0
npm install @code-hike/scrollycoding@0.3.0--canary.32.323f72f.0
npm install …
```

Add release workflow

---

packages/smooth-lines/src/index.tsx
packages/smooth-lines/src/line-transitions.ts
packages/smooth-lines/src/lines.tsx
packages/storybook/src/mini-editor.story.js
packages/storybook/src/smooth-lines.story.js

Fix #24 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.45.6c84da7.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.45.6c84da7.0
npm install @code-hike/code-diff@0.3.0--canary.45.6c84da7.0
npm install @code-hike/mini-browser@0.3.0--canary.45.6c84da7.0
npm install @code-hike/mini-editor@0.3.0--canary.45.6c84da7.0
npm install @code-hike/mini-frame@0.3.0--canary.45.6c84da7.0
npm install @code-hike/mini-terminal@0.3.0--canary.45.6c84da7.0
npm install @code-hike/player@0.3.0--canary.45.6c84da7.0
npm install @code-hike/script@0.3.0--canary.45.6c84da7.0
npm install @code-hike/scroller@0.3.0--canary.45.6c84da7.0
npm install @code-hike/scrollycoding@0.3.0--canary.45.6c84da7.0
npm install …
```

Better centering logic

---

packages/scrollycoding/package.json
packages/scrollycoding/src/code.tsx
packages/scrollycoding/src/demo-context.tsx
packages/scrollycoding/src/hike-context.tsx
packages/scrollycoding/src/index.scss
packages/scrollycoding/src/preview-loader.scss
packages/scrollycoding/src/preview-loader.tsx
packages/scrollycoding/src/preview.tsx
packages/storybook/src/assets/scrollycoding.basic.mdx
yarn.lock

Fix #30 and fix #44 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.47.52daf46.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.47.52daf46.0
npm install @code-hike/code-diff@0.3.0--canary.47.52daf46.0
npm install @code-hike/mini-browser@0.3.0--canary.47.52daf46.0
npm install @code-hike/mini-editor@0.3.0--canary.47.52daf46.0
npm install @code-hike/mini-frame@0.3.0--canary.47.52daf46.0
npm install @code-hike/mini-terminal@0.3.0--canary.47.52daf46.0
npm install @code-hike/player@0.3.0--canary.47.52daf46.0
npm install @code-hike/script@0.3.0--canary.47.52daf46.0
npm install @code-hike/scroller@0.3.0--canary.47.52daf46.0
npm install @code-hike/scrollycoding@0.3.0--canary.47.52daf46.0
npm install …
```

Use new sandpack

---

packages/mini-editor/src/code.tsx
packages/mini-editor/src/index.scss
packages/mini-editor/src/mini-editor.tsx
packages/mini-editor/src/use-dimensions.tsx
packages/smooth-lines/src/index.tsx
packages/storybook/src/mini-editor.story.js
packages/storybook/src/scrollycoding.story.js
packages/storybook/src/smooth-lines.story.js

Fix #48 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.49.d3183ba.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.49.d3183ba.0
npm install @code-hike/code-diff@0.3.0--canary.49.d3183ba.0
npm install @code-hike/mini-browser@0.3.0--canary.49.d3183ba.0
npm install @code-hike/mini-editor@0.3.0--canary.49.d3183ba.0
npm install @code-hike/mini-frame@0.3.0--canary.49.d3183ba.0
npm install @code-hike/mini-terminal@0.3.0--canary.49.d3183ba.0
npm install @code-hike/player@0.3.0--canary.49.d3183ba.0
npm install @code-hike/script@0.3.0--canary.49.d3183ba.0
npm install @code-hike/scroller@0.3.0--canary.49.d3183ba.0
npm install @code-hike/scrollycoding@0.3.0--canary.49.d3183ba.0
npm install …
```

Add scrollbars

---

packages/mini-editor/src/code.tsx
packages/mini-editor/src/mini-editor-hike.tsx
packages/smooth-lines/src/index.tsx
packages/storybook/src/mini-editor-hike.story.js

Fix #57 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.58.8628c34.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.58.8628c34.0
npm install @code-hike/code-diff@0.3.0--canary.58.8628c34.0
npm install @code-hike/mini-browser@0.3.0--canary.58.8628c34.0
npm install @code-hike/mini-editor@0.3.0--canary.58.8628c34.0
npm install @code-hike/mini-frame@0.3.0--canary.58.8628c34.0
npm install @code-hike/mini-terminal@0.3.0--canary.58.8628c34.0
npm install @code-hike/player@0.3.0--canary.58.8628c34.0
npm install @code-hike/script@0.3.0--canary.58.8628c34.0
npm install @code-hike/scroller@0.3.0--canary.58.8628c34.0
npm install @code-hike/scrollycoding@0.3.0--canary.58.8628c34.0
npm install …
```

Add horizontal center prop

---

packages/mini-browser/src/buttons.tsx
packages/mini-browser/src/index.scss
packages/mini-browser/src/mini-browser-hike.tsx
packages/scrollycoding/src/mdx-steps.tsx
packages/scrollycoding/src/preview.tsx

Fix #55 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.59.324d15c.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.59.324d15c.0
npm install @code-hike/code-diff@0.3.0--canary.59.324d15c.0
npm install @code-hike/mini-browser@0.3.0--canary.59.324d15c.0
npm install @code-hike/mini-editor@0.3.0--canary.59.324d15c.0
npm install @code-hike/mini-frame@0.3.0--canary.59.324d15c.0
npm install @code-hike/mini-terminal@0.3.0--canary.59.324d15c.0
npm install @code-hike/player@0.3.0--canary.59.324d15c.0
npm install @code-hike/script@0.3.0--canary.59.324d15c.0
npm install @code-hike/scroller@0.3.0--canary.59.324d15c.0
npm install @code-hike/scrollycoding@0.3.0--canary.59.324d15c.0
npm install …
```

Optional browser transition

---

packages/mini-editor/src/code.tsx
packages/smooth-lines/src/index.tsx
packages/smooth-lines/src/line-transitions.ts
packages/storybook/src/mini-editor-hike.story.js

Fix #60 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.61.e6f2135.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.61.e6f2135.0
npm install @code-hike/code-diff@0.3.0--canary.61.e6f2135.0
npm install @code-hike/mini-browser@0.3.0--canary.61.e6f2135.0
npm install @code-hike/mini-editor@0.3.0--canary.61.e6f2135.0
npm install @code-hike/mini-frame@0.3.0--canary.61.e6f2135.0
npm install @code-hike/mini-terminal@0.3.0--canary.61.e6f2135.0
npm install @code-hike/player@0.3.0--canary.61.e6f2135.0
npm install @code-hike/script@0.3.0--canary.61.e6f2135.0
npm install @code-hike/scroller@0.3.0--canary.61.e6f2135.0
npm install @code-hike/scrollycoding@0.3.0--canary.61.e6f2135.0
npm install …
```

Fix line jumps

---

packages/mdx/src/client/code.tsx
packages/mdx/src/client/scrollycoding.tsx
packages/mdx/src/client/section.tsx
packages/mdx/src/client/spotlight.tsx
packages/mini-editor/src/editor-frame.tsx
packages/playground/content/scrollycoding-demo.mdx
packages/playground/content/section.mdx
packages/playground/content/simple-editor.mdx
packages/playground/content/spotlight-demo.mdx

Fix #28 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.86.f0a55af.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.86.f0a55af.0
npm install @code-hike/highlighter@0.3.0--canary.86.f0a55af.0
npm install @code-hike/mdx@0.3.0--canary.86.f0a55af.0
npm install @code-hike/mini-browser@0.3.0--canary.86.f0a55af.0
npm install @code-hike/mini-editor@0.3.0--canary.86.f0a55af.0
npm install @code-hike/mini-frame@0.3.0--canary.86.f0a55af.0
npm install @code-hike/mini-terminal@0.3.0--canary.86.f0a55af.0
npm install @code-hike/player@0.3.0--canary.86.f0a55af.0
npm install @code-hike/playground@0.3.0--canary.86.f0a55af.0
npm install @code-hike/script@0.3.0--canary.86.f0a55af.0
npm install …
```

Make tabs clickable

---

packages/mdx/src/plugin/annotations.ts
packages/playground/content/comment-annotations.mdx

Stop assuming comment annotations

---

packages/mini-editor/src/editor-frame.tsx
packages/mini-editor/src/editor-shift.tsx
packages/mini-editor/src/editor-tween.tsx
packages/mini-editor/src/index.scss
packages/playground/content/scrollycoding.mdx
packages/playground/content/simple-code.mdx
packages/playground/content/spotlight-demo.mdx
packages/storybook/src/editor-spring.story.js
packages/storybook/src/editor-tween-two.story.js

<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.98.d32feb5.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.98.d32feb5.0
npm install @code-hike/highlighter@0.3.0--canary.98.d32feb5.0
npm install @code-hike/mdx@0.3.0--canary.98.d32feb5.0
npm install @code-hike/mini-browser@0.3.0--canary.98.d32feb5.0
npm install @code-hike/mini-editor@0.3.0--canary.98.d32feb5.0
npm install @code-hike/mini-frame@0.3.0--canary.98.d32feb5.0
npm install @code-hike/mini-terminal@0.3.0--canary.98.d32feb5.0
npm install @code-hike/player@0.3.0--canary.98.d32feb5.0
npm install @code-hike/playground@0.3.0--canary.98.d32feb5.0
npm install @code-hike/script@0.3.0--canary.98.d32feb5.0
npm install …
```

Smarter editor height

---

packages/mdx/src/client/annotations.tsx
packages/mdx/src/client/code.tsx
packages/mdx/src/client/inline-code.tsx
packages/mdx/src/client/preview.tsx
packages/mdx/src/client/scrollycoding.scss
packages/mdx/src/client/scrollycoding.tsx
packages/mdx/src/client/slideshow.scss
packages/mdx/src/client/slideshow.tsx
packages/mdx/src/client/spotlight.scss
packages/mdx/src/client/spotlight.tsx
packages/mdx/src/components.tsx
packages/mdx/src/index.scss
packages/mdx/src/plugin.ts
packages/mdx/src/plugin/inline-code.ts
packages/mdx/src/plugin/preview.ts
packages/mdx/src/plugin/unist-utils.ts
packages/mini-browser/package.json
packages/mini-browser/src/buttons.tsx
packages/mini-browser/src/mini-browser-hike.tsx
packages/mini-browser/src/title-bar.tsx
packages/mini-editor/src/editor-frame.tsx
packages/mini-editor/src/index.scss
packages/mini-frame/package.json
packages/mini-frame/src/index.scss
packages/mini-frame/src/mini-frame.tsx
packages/mini-terminal/src/mini-terminal-transition.tsx
packages/playground/content/simple-code.mdx
packages/playground/content/test.mdx
packages/smooth-code/src/code-tween.tsx
packages/utils/src/theme.ts

<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.116.056ec02.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.116.056ec02.0
npm install @code-hike/highlighter@0.3.0--canary.116.056ec02.0
npm install @code-hike/mdx@0.3.0--canary.116.056ec02.0
npm install @code-hike/mini-browser@0.3.0--canary.116.056ec02.0
npm install @code-hike/mini-editor@0.3.0--canary.116.056ec02.0
npm install @code-hike/mini-frame@0.3.0--canary.116.056ec02.0
npm install @code-hike/mini-terminal@0.3.0--canary.116.056ec02.0
npm install @code-hike/player@0.3.0--canary.116.056ec02.0
npm install @code-hike/playground@0.3.0--canary.116.056ec02.0
npm install @code-hike/script@0.3.0--canary.116.056ec02.0
npm install …
```

Better default styles

---

packages/smooth-code/src/code-spring.tsx
packages/smooth-code/src/code-tween.tsx

Fix #120 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.124.5b2426a.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.124.5b2426a.0
npm install @code-hike/highlighter@0.3.0--canary.124.5b2426a.0
npm install @code-hike/mdx@0.3.0--canary.124.5b2426a.0
npm install @code-hike/mini-browser@0.3.0--canary.124.5b2426a.0
npm install @code-hike/mini-editor@0.3.0--canary.124.5b2426a.0
npm install @code-hike/mini-frame@0.3.0--canary.124.5b2426a.0
npm install @code-hike/mini-terminal@0.3.0--canary.124.5b2426a.0
npm install @code-hike/player@0.3.0--canary.124.5b2426a.0
npm install @code-hike/playground@0.3.0--canary.124.5b2426a.0
npm install @code-hike/script@0.3.0--canary.124.5b2426a.0
npm install …
```

Fix firefox copypasting

---

packages/highlighter/src/index.tsx
packages/playground/content/simple-code.mdx

Fix #122
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.126.19a4397.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.126.19a4397.0
npm install @code-hike/highlighter@0.3.0--canary.126.19a4397.0
npm install @code-hike/mdx@0.3.0--canary.126.19a4397.0
npm install @code-hike/mini-browser@0.3.0--canary.126.19a4397.0
npm install @code-hike/mini-editor@0.3.0--canary.126.19a4397.0
npm install @code-hike/mini-frame@0.3.0--canary.126.19a4397.0
npm install @code-hike/mini-terminal@0.3.0--canary.126.19a4397.0
npm install @code-hike/player@0.3.0--canary.126.19a4397.0
npm install @code-hike/playground@0.3.0--canary.126.19a4397.0
npm install @code-hike/script@0.3.0--canary.126.19a4397.0
npm install …
```

Handle invalid language

---

examples/nextjs/pages/my.md
packages/mdx/package.json
packages/mdx/rollup.config.js

Fix #156
<details>
<summary>📦 Published PR as canary version: <code>0.4.0--canary.157.99e69b4.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.4.0--canary.157.99e69b4.0
yarn add @code-hike/mdx@0.4.0--canary.157.99e69b4.0
```
</details>

Rename esm to .mjs

---

.github/workflows/bundle_analysis.yml
.github/workflows/nextjs_bundle_analysis.yml
examples/bundle-test/.gitignore
examples/bundle-test/next.config.js
examples/bundle-test/package.json
examples/bundle-test/pages/_app.js
examples/bundle-test/pages/js-page.js
examples/bundle-test/pages/just-code.mdx
examples/bundle-test/pages/no-ch-mdx.mdx
examples/bundle-test/pages/scrollycoding-preview.mdx
examples/bundle-test/pages/spotlight.mdx
package.json
packages/mdx/src/components.tsx
packages/mdx/src/index.tsx

<details>
<summary>📦 Published PR as canary version: <code>0.4.0--canary.159.6e65f8e.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.4.0--canary.159.6e65f8e.0
yarn add @code-hike/mdx@0.4.0--canary.159.6e65f8e.0
```
</details>

Export internals

---

.github/workflows/bundle_analysis.yml
examples/bundle-test/package.json
examples/bundle-test/pages/js-page.js
examples/bundle-test/pages/no-ch-mdx.mdx
examples/nextjs/package.json
examples/nextjs/pages/scrolly.mdx
packages/mdx/package.json
packages/mdx/rollup.config.js
packages/mdx/src/components.tsx
packages/mdx/src/mdx-plugin/ch-usage.ts
packages/mdx/src/mdx-plugin/plugin.ts
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>0.4.0--canary.160.509154a.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.4.0--canary.160.509154a.0
yarn add @code-hike/mdx@0.4.0--canary.160.509154a.0
```
</details>

Smart imports

---

packages/mdx/dev/content/comment-annotations.mdx
packages/mdx/src/mdx-client/annotations.tsx

<details>
<summary>📦 Published PR as canary version: <code>0.5.0--canary.169.a3b677d.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.5.0--canary.169.a3b677d.0
yarn add @code-hike/mdx@0.5.0--canary.169.a3b677d.0
```
</details>

Remove target from code links

---

packages/mdx/package.json
packages/mdx/rollup.config.js
packages/mdx/src/mdx-client/code.tsx
packages/mdx/tsconfig.json
yarn.lock

Merges all `.d.ts` files (closes #148)
I had to disable `declaration` in tsconfig to prevent `rollup-plugin-typescript2` from creating the declarations.
Note: I also give a try in using `@rollup/plugin-typescript`, but it required much more configuration changes and had warnings I could not solve. I attach a screenshot of some of them. For example the `sourcemap` warning was no way to get rid of, not even adding `output.sourcemap = true` in rollupconfig as it says.. 
This is the result: the new dist folder looks much cleaner.
Old:
New:
This is the content of the new generated files:
<details>
<summary>Content of `index.d.ts`</summary>
```ts
interface Data {
[key: string]: unknown;
}
interface GenericNode<TData extends object = Data> {
/**
* The variant of a node.
*/
type: string;
/**
* …
```

Modify output of dist folder to merge all .d.ts files

---

packages/mdx/dev/files.ts
packages/mdx/src/mini-editor/editor-frame.tsx
packages/mdx/src/remark/comment-data.ts
playground/src/app.jsx

Fix #171 
<details>
<summary>📦 Published PR as canary version: <code>0.5.2--canary.188.6d4af01.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.5.2--canary.188.6d4af01.0
yarn add @code-hike/mdx@0.5.2--canary.188.6d4af01.0
```
</details>

Fix rose pine themes

---

packages/mdx/src/mdx-client/scrollycoding.scss
packages/mdx/src/mdx-client/scrollycoding.tsx
packages/mdx/src/mdx-client/section.tsx
packages/mdx/src/mdx-client/slideshow.tsx
packages/mdx/src/mdx-client/spotlight.scss
packages/mdx/src/mdx-client/spotlight.tsx
packages/mdx/src/remark/transform.section.ts

Styling props

---

packages/mdx/dev/files.ts
packages/mdx/src/remark/code.ts
packages/mdx/src/remark/config.ts
packages/mdx/src/remark/steps.tsx
packages/mdx/src/remark/transform.code.ts
packages/mdx/src/remark/transform.section.ts

Add `skipLanguages` to Code Hike config. Fix #210 
<details>
<summary>📦 Published PR as canary version: <code>0.6.2--canary.213.47834b0.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.6.2--canary.213.47834b0.0
yarn add @code-hike/mdx@0.6.2--canary.213.47834b0.0
```
</details>

Add skipLanguages config

---

packages/mdx/dev/content/assets/foo.js
packages/mdx/dev/content/assets/foo.py
packages/mdx/dev/content/external.mdx
packages/mdx/dev/files.ts
packages/mdx/pages/[name].tsx
packages/mdx/src/remark/code.ts
packages/mdx/src/remark/comment-data.ts
packages/mdx/src/remark/config.ts
packages/mdx/src/remark/transform.ts
playground/src/index.css

Fix #211 
<details>
<summary>📦 Published PR as canary version: <code>0.6.2--canary.214.f73c87d.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.6.2--canary.214.f73c87d.0
yarn add @code-hike/mdx@0.6.2--canary.214.f73c87d.0
```
</details>

Add from annotation

---

packages/mdx/dev/content/test.mdx
packages/mdx/src/mdx-client/code.tsx
packages/mdx/src/smooth-code/code-tween.tsx
packages/mdx/src/smooth-code/index.scss
packages/mdx/src/smooth-code/smooth-container.tsx
packages/mdx/src/smooth-code/use-dimensions.tsx

Fix #196 
<details>
<summary>📦 Published PR as canary version: <code>0.6.2--canary.216.fcee42a.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.6.2--canary.216.fcee42a.0
yarn add @code-hike/mdx@0.6.2--canary.216.fcee42a.0
```
</details>

Better scrollbars

---

packages/mdx/dev/content/test.mdx
packages/mdx/src/mdx-client/scrollycoding.tsx
packages/mdx/src/mdx-client/slideshow.tsx
packages/mdx/src/mdx-client/spotlight.tsx
packages/mdx/src/mdx-client/steps.tsx
packages/mdx/src/remark/steps.tsx
packages/mdx/src/remark/transform.scrollycoding.ts
packages/mdx/src/remark/transform.slideshow.ts
packages/mdx/src/remark/transform.spotlight.ts

<details>
<summary>📦 Published PR as canary version: <code>0.7.0--canary.221.c178263.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.0--canary.221.c178263.0
yarn add @code-hike/mdx@0.7.0--canary.221.c178263.0
```
</details>

Add previews in steps

---

packages/mdx/src/smooth-code/use-dimensions.tsx

Fix #232 
<details>
<summary>📦 Published PR as canary version: <code>0.7.1--canary.233.82f2055.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.1--canary.233.82f2055.0
yarn add @code-hike/mdx@0.7.1--canary.233.82f2055.0
```
</details>

Set `longestLineRef` once

---

.gitignore
packages/mdx/dev/content/slideshow-autofocus.mdx
packages/mdx/src/mdx-client/slideshow.tsx

Resolves #244 
Feel free to decline if you do not think we should add this. Or if you would like to suggest a different approach, I am happy to make some modifications.

feat(244): Allow Slideshow controls to autoFocus

---

.gitignore
packages/mdx/package.json
packages/mdx/rollup.config.js
packages/mdx/src/components.tsx
packages/mdx/src/index.tsx
packages/mdx/src/mdx-client/annotations.tsx
packages/mdx/src/remark/transform.ts

Fix #237
<details>
<summary>📦 Published PR as canary version: <code>0.7.3--canary.249.1f1c8a2.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.3--canary.249.1f1c8a2.0
yarn add @code-hike/mdx@0.7.3--canary.249.1f1c8a2.0
```
</details>

Fix typescript module resolution

---

packages/mdx/dev/content/slideshow-onchange.mdx
packages/mdx/src/mdx-client/slideshow.tsx
packages/mdx/src/utils/hooks.ts

Resolves #246 
For the proposed use case, it is not enough to only initialize the Slideshow component with a starting slide. There also needed to be a way to expose the current slide so that someone could use that value to set in the current URL.
- Adds an `initialSlideIndex` prop which allows initializing CH.Slideshow on a specific slide
- Includes a new `useInitialState` hook which is used to make sure changing the initialSlideIndex after mount would not control the component
- Includes a check to make sure the initial slide does not get set greater than the max slides in the MDX file
- Includes MDX example of this prop in use
- Adds an `onChange` function to the CH.Slideshow component which will get called every time the internal Slideshow state changes, and will return the internal …

feat(#246): Add onChange and initialSlideIndex props to CH.Slideshow

---

packages/mdx/src/remark/transform.ts

Fix #252 
<details>
<summary>📦 Published PR as canary version: <code>0.7.3--canary.256.a2aa5ff.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.3--canary.256.a2aa5ff.0
yarn add @code-hike/mdx@0.7.3--canary.256.a2aa5ff.0
```
</details>

Change plugin type

---

packages/mdx/dev/content/rows.mdx
packages/mdx/src/mdx-client/code.tsx
packages/mdx/src/smooth-code/code-tween.tsx
packages/mdx/src/smooth-code/use-dimensions.tsx
packages/mdx/src/utils/focus.ts

Fix #258
Forcing 4 lines of height:
````md
<CH.Code rows={4}>
```js
console.log(1)
console.log(2)
console.log(3)
console.log(4)
console.log(5)
console.log(6)
console.log(7)
```
</CH.Code>
````
Forcing the height to match the focused code:
````md
<CH.Code rows="focus">
```js focus=3:4,6
console.log(1)
console.log(2)
console.log(3)
console.log(4)
console.log(5)
console.log(6)
console.log(7)
```
</CH.Code>
````
<details>
<summary>📦 Published PR as canary version: <code>0.7.3--canary.262.fb2e24d.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.3--canary.262.fb2e24d.0
yarn add @code-hike/mdx@0.7.3--canary.262.fb2e24d.0
```
</details>

Change code height with `rows`

---

packages/mdx/src/smooth-code/code-tween.tsx

Fix #240 
<details>
<summary>📦 Published PR as canary version: <code>0.7.4--canary.267.6ac2b96.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.4--canary.267.6ac2b96.0
yarn add @code-hike/mdx@0.7.4--canary.267.6ac2b96.0
```
</details>

Force content box in code-wrapper

---

packages/mdx/src/mini-editor/code-browser.scss
packages/mdx/src/mini-editor/dialog.scss
packages/mdx/src/mini-editor/editor-frame.tsx
packages/mdx/src/mini-editor/expand-button.tsx
packages/mdx/src/mini-editor/index.scss
packages/mdx/src/smooth-code/copy-button.tsx
packages/mdx/src/smooth-code/index.scss
packages/mdx/src/utils/mixins.scss

especially for accessibility reasons; to e.g. have those announced correctly by screenreaders and even also make them reachable on keyboard usage.
Resolves https://github.com/code-hike/codehike/issues/335

fix: use semantic elements

---

packages/mdx/src/utils/mixins.scss

A small change to improve the accessibility of the copy buttons,  followin up #341
Here I'm making sure the buttons show a visible outline when focused on using the keyboard

add outline-color to button-reset mixin 

---

packages/mdx/dev/content/comment-annotations.mdx
packages/mdx/dev/files.ts
packages/mdx/dev/theme.js
packages/mdx/src/index.scss
packages/mdx/src/mdx-client/annotations.tsx
packages/mdx/src/smooth-code/partial-step-parser.ts
packages/mdx/src/smooth-code/smooth-lines.tsx

Fix #351
<details>
<summary>📦 Published PR as canary version: <code>0.8.3--canary.357.aa719d3.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.8.3--canary.357.aa719d3.0
yarn add @code-hike/mdx@0.8.3--canary.357.aa719d3.0
```
</details>

Add copy button to multiline mark

---

packages/mdx/src/mdx-client/scrollycoding.tsx
packages/mdx/src/scroller/index.tsx
packages/mdx/src/smooth-code/code-tween.tsx

<details>
<summary>📦 Published PR as canary version: <code>0.8.3--canary.360.f91c849.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.8.3--canary.360.f91c849.0
yarn add @code-hike/mdx@0.8.3--canary.360.f91c849.0
```
</details>

Add trigger position config

---

packages/mdx/src/highlighter/index.tsx
packages/mdx/src/smooth-code/code-tween.tsx
packages/mdx/src/smooth-code/index.scss
packages/mdx/src/smooth-code/use-dimensions.tsx

Fix #372, fix #371, fix #340, fix #319, fix #279.
If the code starts hidden (for example, inside an inactive tab) use a ResizeObserver to recalculate dimensions when it's displayed later.
<details>
<summary>📦 Published PR as canary version: <code>0.9.0--canary.373.22ed7cb.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.9.0--canary.373.22ed7cb.0
yarn add @code-hike/mdx@0.9.0--canary.373.22ed7cb.0
```
</details>

Fix dimensions when code starts hidden

---

packages/mdx/dev/content/assets/bar.js
packages/mdx/dev/content/external.mdx
packages/mdx/src/remark/code.ts

Fix #375 
Now it's possible to include a range of lines using the `from` annotation (range starts at 1, not 0).
````md
```py
```
````

`from` annotation with line range

---

package.json

Fix #382
<details>
<summary>📦 Published PR as canary version: <code>0.9.1--canary.383.d0587aa.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.9.1--canary.383.d0587aa.0
yarn add @code-hike/mdx@0.9.1--canary.383.d0587aa.0
```
</details>

Add new release message

---

packages/mdx/dev/content/scrollycoding-demo.mdx
packages/mdx/dev/content/static-toggle.mdx
packages/mdx/src/components.tsx
packages/mdx/src/highlighter/index.tsx
packages/mdx/src/mdx-client/scrollycoding.tsx
packages/mdx/src/mdx-client/ssmq.tsx

Export `<CH.StaticToggle />` to force the static version.
<details>
<summary>📦 Published PR as canary version: <code>0.9.1--canary.395.984614e.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.9.1--canary.395.984614e.0
yarn add @code-hike/mdx@0.9.1--canary.395.984614e.0
```
</details>

Add static toggle

---

packages/mdx/dev/content/scrollycoding-demo.mdx
packages/mdx/src/mini-editor/code-browser.tsx
packages/mdx/src/mini-editor/dialog.scss
packages/mdx/src/mini-editor/editor-tween.tsx
packages/mdx/src/mini-editor/expand-button.tsx
packages/mdx/src/smooth-code/code-tween.tsx
packages/mdx/src/smooth-code/index.scss

Allow expand button in codeblocks.
Fix #386
<details>
<summary>📦 Published PR as canary version: <code>0.9.1--canary.396.08be59d.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.9.1--canary.396.08be59d.0
yarn add @code-hike/mdx@0.9.1--canary.396.08be59d.0
```
</details>

Add expand button to codeblocks

---

packages/mdx/dev/content/scrollycoding-demo.mdx
packages/mdx/src/smooth-code/use-dimensions.tsx

Don't chante dimensions when the focus changes.
<details>
<summary>📦 Published PR as canary version: <code>0.9.1--canary.397.c7a9d9d.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.9.1--canary.397.c7a9d9d.0
yarn add @code-hike/mdx@0.9.1--canary.397.c7a9d9d.0
```
</details>

Stable dimensions

---

packages/mdx/dev/content/test.mdx
packages/mdx/package.json
yarn.lock

Support ansi codes in terminal codeblocks:
````mdx
```terminal 
[35m❯[0m npm create astro -y
╭─────╮  [36;1mHouston:
[0m│ ◠ [96m◡[0m ◠  Initiating launch sequence...
╰─────╯
[42m [30mastro[39m [0m  [32;1mv2.9.2[0m [1mLaunch sequence initiated.
[0m  [48;2;136;58;226m [97mdir[39m [0m  Where should we create your new project?
[2m./cosmic-chroma
[0m [48;2;136;58;226m [97mtmpl[39m [0m  How would you like to start your new project?
[2mEmpty
[0m      [32m✔[0m  [32mTemplate copied
[0m [48;2;136;58;226m [97mdeps[39m [0m  Install dependencies?
[2mNo
[0m      [36m◼[0m  [36mNo problem!
[0m         [2mRemember to install dependencies after setup.
[0m   [48;2;136;58;226m [97mts[39m [0m  Do you plan to write TypeScript?
[2mNo
[0m      [36m◼[0m  [36mNo …

Terminal highlighting

---

apps/web/content/blog/fine-grained/scrolly.tsx

When using relative, the StepMessage container blocks the selection of the code block.
The same overlapping effect can be achieved with the a z-index while allowing the user to copy and paste text from both the message and code block.

Use z-index instead of relative to enable text selection

---

apps/web/app/docs/[[...slug]]/preview-implementation.tsx
apps/web/components/component-pack-link.tsx
apps/web/content/blog/content-presentation-gap.mdx
apps/web/content/blog/content-presentation-gap.tsx
apps/web/content/blog/the-curse-of-markdown.mdx
apps/web/content/docs/api.mdx
apps/web/content/docs/api.tsx
apps/web/content/docs/api/code.mdx
apps/web/content/docs/api/hike.mdx
apps/web/content/docs/api/schema.mdx

Add API reference page

---

apps/web/demos/focus/code.tsx
apps/web/demos/hover/page.tsx

Hi there, thanks for the great work! I noticed that the [code mention](https://codehike.org/docs/code/code-mentions) and [focus](https://codehike.org/docs/code/focus) examples have low text contrast in light mode, so I created a fix for it. Feel free to close this if I missed something obvious.

Improve text contrast for hover and focus examples in light mode

---

.changeset/silent-shoes-add.md
apps/web/content/docs/concepts/assets/index.js
apps/web/content/docs/concepts/code.mdx
packages/codehike/src/mdx/0.import-code-from-path.ts
packages/codehike/tests/md-suite/_readme.md
packages/codehike/tests/md-suite/assets/test.py
packages/codehike/tests/md-suite/import-code.0.mdx
packages/codehike/tests/md-suite/import-code.0.render.tsx
packages/codehike/tests/md-suite/import-code.7.compiled-jsx.jsx
packages/codehike/tests/md-suite/import-code.9.rendered.html

Fix #439
Now we can mix `!from` with more code, annotations, or even more `!from` directives
````md
```py
!from ./assets/test.py
def hello():
print("hello")
!from ./assets/test.py
```
````

More flexible !from directive

---

.changeset/loud-moons-grow.md
packages/codehike/src/code/extract-annotations.test.ts
packages/codehike/src/code/extract-annotations.tsx

Now, regex in annotation ranges allow escaped `[]` and `()`.
So it supports cases like this:
````
```jsx
// !Fold[/className="([^"]+)"/g]
function Foo() {
return (
<div className="bg-red-200 opacity-50">
<span className="border">hey</span>
</div>
)
}
```
````

Better regex parsing in annotation range
