code-hike/codehike

- packages/mini-editor/src/editor-frame.tsx
- site/pages/demo/swr.js
- site/src/demo-swr/index.js
- site/src/demo-swr/index.module.css
- site/src/demo-swr/steps.js
- site/src/demo-swr/steps/0.js
- site/src/demo-swr/steps/1.js
- site/src/demo-swr/steps/2.js
- site/src/demo-swr/steps/3.js
- site/src/demo-swr/steps/4.js
- site/src/demo-swr/steps/5.js
- site/src/demo-swr/steps/6.js
Using the design from Apple's mobile landing page to create a "mini docs" page.
> SWR MiniDocs Demo

- .github/workflows/release.yml
- package.json
- yarn.lock
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.34.f4f0bfe.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/code-diff@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/mini-browser@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/mini-editor@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/mini-frame@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/mini-terminal@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/player@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/script@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/scroller@0.3.0--canary.34.f4f0bfe.0
npm install @code-hike/scrollycoding@0.3.0--canary.34.f4f0bfe.0
npm install …
```
> Turn onlyPublishWithReleaseLabel on

- package.json
- yarn.lock
> Bump auto version

- .github/workflows/release.yml
- packages/classer/package.json
- packages/code-diff/package.json
- packages/mini-browser/package.json
- packages/mini-editor/package.json
- packages/mini-frame/package.json
- packages/mini-terminal/package.json
- packages/player/package.json
- packages/script/build.js
- packages/script/package.json
- packages/script/rollup.config.js
- packages/scroller/package.json
- packages/scrollycoding/package.json
- packages/sim-user/package.json
- packages/smooth-column/package.json
- packages/smooth-lines/package.json
- yarn.lock
> Better release log

- packages/mini-editor/src/code.tsx
- packages/smooth-lines/src/lines.tsx
> Fix copy paste

- packages/classer/package.json
- packages/code-diff/package.json
- packages/mini-browser/package.json
- packages/mini-editor/package.json
- packages/mini-editor/src/mini-editor-spring.tsx
- packages/mini-frame/package.json
- packages/mini-terminal/package.json
- packages/player/package.json
- packages/scroller/package.json
- packages/scrollycoding/package.json
- packages/scrollycoding/src/editor.tsx
- packages/scrollycoding/src/focus.tsx
- packages/scrollycoding/src/hike.tsx
- packages/sim-user/package.json
- packages/smooth-code/package.json
- packages/smooth-column/package.json
- packages/smooth-lines/package.json
- packages/storybook/src/scrollycoding.story.js
- yarn.lock
Fix #74 and #73 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.75.9e3cd0e.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/code-diff@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/mini-browser@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/mini-editor@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/mini-frame@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/mini-terminal@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/player@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/script@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/scroller@0.3.0--canary.75.9e3cd0e.0
npm install @code-hike/scrollycoding@0.3.0--canary.75.9e3cd0e.0
npm install …
```
> Add spring config

- packages/mdx/src/client/slideshow.scss
- packages/mdx/src/client/slideshow.tsx
- packages/mdx/src/components.tsx
- packages/mdx/src/index.scss
- packages/mdx/src/plugin.ts
- packages/mdx/src/plugin/slideshow.ts
- packages/mini-browser/src/index.scss
- packages/playground/content/slideshow-demo.mdx
- packages/playground/content/slideshow.mdx
- packages/smooth-code/src/smooth-container.tsx
- packages/smooth-code/src/use-dimensions.tsx
- packages/storybook/src/code-tween.story.js
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.99.4abcdea.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.99.4abcdea.0
npm install @code-hike/highlighter@0.3.0--canary.99.4abcdea.0
npm install @code-hike/mdx@0.3.0--canary.99.4abcdea.0
npm install @code-hike/mini-browser@0.3.0--canary.99.4abcdea.0
npm install @code-hike/mini-editor@0.3.0--canary.99.4abcdea.0
npm install @code-hike/mini-frame@0.3.0--canary.99.4abcdea.0
npm install @code-hike/mini-terminal@0.3.0--canary.99.4abcdea.0
npm install @code-hike/player@0.3.0--canary.99.4abcdea.0
npm install @code-hike/playground@0.3.0--canary.99.4abcdea.0
npm install @code-hike/script@0.3.0--canary.99.4abcdea.0
npm install …
```
> Slideshow component

- packages/highlighter/src/index.tsx
- packages/mdx/src/plugin/code.ts
- packages/playground/content/simple-code.mdx
Allow mdx like this
~~~md
```
This codeblock has no language
```
~~~
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.103.faafeb2.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.103.faafeb2.0
npm install @code-hike/highlighter@0.3.0--canary.103.faafeb2.0
npm install @code-hike/mdx@0.3.0--canary.103.faafeb2.0
npm install @code-hike/mini-browser@0.3.0--canary.103.faafeb2.0
npm install @code-hike/mini-editor@0.3.0--canary.103.faafeb2.0
npm install @code-hike/mini-frame@0.3.0--canary.103.faafeb2.0
npm install @code-hike/mini-terminal@0.3.0--canary.103.faafeb2.0
npm install @code-hike/player@0.3.0--canary.103.faafeb2.0
npm install @code-hike/playground@0.3.0--canary.103.faafeb2.0
npm install …
```
> Allow empty lang

- packages/mdx/src/plugin/annotations.ts
- packages/playground/content/comment-annotations.mdx
Fix #104 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.105.d3f27ad.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/highlighter@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/mdx@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/mini-browser@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/mini-editor@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/mini-frame@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/mini-terminal@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/player@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/playground@0.3.0--canary.105.d3f27ad.0
npm install @code-hike/script@0.3.0--canary.105.d3f27ad.0
npm install …
```
> Fix annotation regex

- packages/smooth-code/src/code-tween.tsx
- packages/smooth-code/src/index.scss
- packages/utils/src/theme.ts
> Selection color from theme

- packages/smooth-code/src/code-tween.tsx
Same as https://github.com/code-hike/codehike/issues/132.
> Changes style property to fix 'Unsupported style property color-scheme'

- packages/smooth-code/src/index.scss
for better compat with nextra
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.136.91e3d56.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.136.91e3d56.0
npm install @code-hike/highlighter@0.3.0--canary.136.91e3d56.0
npm install @code-hike/mdx@0.3.0--canary.136.91e3d56.0
npm install @code-hike/mini-browser@0.3.0--canary.136.91e3d56.0
npm install @code-hike/mini-editor@0.3.0--canary.136.91e3d56.0
npm install @code-hike/mini-frame@0.3.0--canary.136.91e3d56.0
npm install @code-hike/mini-terminal@0.3.0--canary.136.91e3d56.0
npm install @code-hike/player@0.3.0--canary.136.91e3d56.0
npm install @code-hike/playground@0.3.0--canary.136.91e3d56.0
npm install @code-hike/script@0.3.0--canary.136.91e3d56.0 …
```
> Reset some code styles

- packages/mdx/src/plugin.ts
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.137.04897c8.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.137.04897c8.0
npm install @code-hike/highlighter@0.3.0--canary.137.04897c8.0
npm install @code-hike/mdx@0.3.0--canary.137.04897c8.0
npm install @code-hike/mini-browser@0.3.0--canary.137.04897c8.0
npm install @code-hike/mini-editor@0.3.0--canary.137.04897c8.0
npm install @code-hike/mini-frame@0.3.0--canary.137.04897c8.0
npm install @code-hike/mini-terminal@0.3.0--canary.137.04897c8.0
npm install @code-hike/player@0.3.0--canary.137.04897c8.0
npm install @code-hike/playground@0.3.0--canary.137.04897c8.0
npm install @code-hike/script@0.3.0--canary.137.04897c8.0
npm install …
```
> Add autoImport setting

- packages/mdx/src/client/slideshow.scss
- packages/mdx/src/index.scss
Fix #140 
<details>
<summary>📦 Published PR as canary version: <code>0.3.0--canary.143.e149ea9.0</code></summary>
<br />
```bash
npm install @code-hike/classer@0.3.0--canary.143.e149ea9.0
npm install @code-hike/highlighter@0.3.0--canary.143.e149ea9.0
npm install @code-hike/mdx@0.3.0--canary.143.e149ea9.0
npm install @code-hike/mini-browser@0.3.0--canary.143.e149ea9.0
npm install @code-hike/mini-editor@0.3.0--canary.143.e149ea9.0
npm install @code-hike/mini-frame@0.3.0--canary.143.e149ea9.0
npm install @code-hike/mini-terminal@0.3.0--canary.143.e149ea9.0
npm install @code-hike/player@0.3.0--canary.143.e149ea9.0
npm install @code-hike/playground@0.3.0--canary.143.e149ea9.0
npm install @code-hike/script@0.3.0--canary.143.e149ea9.0
npm install …
```
> Fix quirks mode height

- examples/browser/index.html
- packages/mdx/package.json
- packages/mdx/rollup.config.js
- packages/mdx/src/highlighter/index.tsx
- yarn.lock
<details>
<summary>📦 Published PR as canary version: <code>0.4.0--canary.154.ea2f836.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.4.0--canary.154.ea2f836.0
yarn add @code-hike/mdx@0.4.0--canary.154.ea2f836.0
```
</details>
> Browser example

- packages/mdx/src/mini-editor/code-browser.tsx
> Improve code-browser

- packages/mdx/src/smooth-code/code-tween.tsx
- packages/mdx/src/smooth-code/partial-step-parser.ts
- packages/mdx/src/smooth-code/smooth-container.tsx
- packages/mdx/src/utils/tween.ts
Fix #239
<details>
<summary>📦 Published PR as canary version: <code>0.7.3--canary.253.e697cd6.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.3--canary.253.e697cd6.0
yarn add @code-hike/mdx@0.7.3--canary.253.e697cd6.0
```
</details>
> Add lang attribute

- packages/mdx/src/smooth-code/splitter.tsx
> Fix focus height on transitions

- packages/mdx/src/smooth-code/use-dimensions.tsx
Fix #277 
<details>
<summary>📦 Published PR as canary version: <code>0.7.5--canary.278.59b2af1.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.7.5--canary.278.59b2af1.0
yarn add @code-hike/mdx@0.7.5--canary.278.59b2af1.0
```
</details>
> Fix line number horizontal shift

- packages/mdx/package.json
- packages/mdx/src/highlighter/index.tsx
- playground/src/index.css
- playground/src/preview.jsx
- yarn.lock
> Catch lighter error

- packages/mdx/dev/content/autolink.mdx
- packages/mdx/dev/files.ts
- packages/mdx/src/remark/annotations.ts
- packages/mdx/src/remark/code.ts
- packages/mdx/src/remark/config.ts
- playground/src/app.jsx
- playground/src/editor.jsx
Fix #356
<details>
<summary>📦 Published PR as canary version: <code>0.8.3--canary.358.345ae60.0</code></summary>
<br />
```bash
npm install @code-hike/mdx@0.8.3--canary.358.345ae60.0
yarn add @code-hike/mdx@0.8.3--canary.358.345ae60.0
```
</details>
> Autolink option

- packages/mdx/src/mini-editor/code-browser.tsx
> Fix empty lines in expand code browser

- examples/nextra/package.json
- packages/mdx/src/utils/mixins.scss
- yarn.lock
> Update nextra example

- .changeset/violet-insects-melt.md
- packages/codehike/package.json
- packages/codehike/src/code.tsx
> Use type wildcards for moduleResolution node compatibility

- apps/web/content/docs/code/collapse.mdx
- apps/web/content/docs/code/language-switcher.mdx
- apps/web/content/docs/code/tabs.mdx
- apps/web/content/docs/code/tooltip.mdx
> Update shadcn command

- .changeset/friendly-rockets-teach.md
- apps/web/content/blog/the-curse-of-markdown.mdx
- apps/web/content/blog/the-curse-of-markdown.tsx
- packages/codehike/src/mdx/1.0.transform-hikes.ts
- packages/codehike/src/mdx/1.1.remark-list-to-section.ts
> Don't fail with `undefined` `children` in remark plugin

- apps/web/content/docs/index.mdx
Found a small typo. Hope you don’t mind. Thanks for working on this project!
---
💖
> fix(docs): small typo
